# Generated by Django 3.0.14 on 2021-12-14 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='firstname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='account',
            name='secondname',
            field=models.CharField(max_length=50),
        ),
    ]
