# Generated by Django 3.0.14 on 2021-12-15 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='house_name',
            new_name='name',
        ),
    ]
