# Generated by Django 3.2 on 2021-12-21 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_address_address_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='is_active',
            field=models.IntegerField(default=False),
        ),
    ]
