# Generated by Django 3.0.14 on 2021-12-13 07:00

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_price', models.IntegerField()),
                ('product_stock', models.IntegerField()),
                ('product_description', models.TextField(max_length=500)),
                ('product_img_1', models.ImageField(upload_to=products.models.filepath)),
                ('product_img_2', models.ImageField(upload_to=products.models.filepath)),
                ('product_img_3', models.ImageField(upload_to=products.models.filepath)),
                ('product_img_4', models.ImageField(upload_to=products.models.filepath)),
                ('product_img_5', models.ImageField(upload_to=products.models.filepath)),
            ],
        ),
    ]
