# Generated by Django 3.0.14 on 2021-12-14 11:20

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='wlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_price', models.IntegerField()),
                ('product_img', models.ImageField(upload_to=products.models.filepath)),
                ('products', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='products.products')),
            ],
        ),
    ]
