# Generated by Django 3.0.14 on 2021-12-14 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_wlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wlist',
            name='product_img',
        ),
        migrations.RemoveField(
            model_name='wlist',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='wlist',
            name='product_price',
        ),
    ]
