# Generated by Django 3.2 on 2021-12-21 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_address_is_active'),
        ('products', '0009_orderitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.address'),
        ),
        migrations.DeleteModel(
            name='order_details',
        ),
    ]
