# Generated by Django 3.2 on 2021-12-25 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_order_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='discount',
            field=models.IntegerField(default=1),
        ),
    ]
