# Generated by Django 3.2 on 2021-12-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_category_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='offer_price',
            field=models.IntegerField(default=False),
        ),
    ]
