# Generated by Django 3.2 on 2021-12-26 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_products_offer_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(max_length=50)),
                ('coupon_discount', models.FloatField()),
                ('coupon_is_active', models.IntegerField()),
            ],
        ),
    ]
