# Generated by Django 3.2 on 2021-12-26 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='coupon_is_active',
            field=models.IntegerField(default=True),
        ),
    ]
