# Generated by Django 3.2 on 2021-12-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_coupon_coupon_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='couopon_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_sum', models.CharField(max_length=50)),
                ('coupon_discount', models.CharField(max_length=50)),
                ('grand_total', models.CharField(max_length=50)),
            ],
        ),
    ]
