# Generated by Django 3.2 on 2021-12-27 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_couopon_list'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='couopon_list',
            new_name='coupon_list',
        ),
    ]
