# Generated by Django 3.2 on 2021-12-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_rename_couopon_list_coupon_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycart',
            name='grand_total',
            field=models.FloatField(default=True),
        ),
    ]
