# Generated by Django 3.2 on 2021-12-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_mycart_grand_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycart',
            name='coupon_discount',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='mycart',
            name='grand_total',
            field=models.CharField(default=True, max_length=50),
        ),
    ]
