# Generated by Django 3.2 on 2021-12-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20211227_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycart',
            name='discount_total',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='mycart',
            name='grand_total',
            field=models.FloatField(default=True),
        ),
    ]
