# Generated by Django 3.2 on 2021-12-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20211227_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycart',
            name='discount_total',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
