# Generated by Django 3.2 on 2021-12-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_alter_mycart_discount_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycart',
            name='coupon_discount',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
