# Generated by Django 3.2 on 2021-12-27 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0023_auto_20211227_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='status',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='user',
        ),
        migrations.AddField(
            model_name='coupon_list',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='coupon_list',
            name='user',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
