# Generated by Django 3.2 on 2021-12-27 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_coupon_list_coupon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon_list',
            old_name='coupon',
            new_name='coupons',
        ),
    ]
