# Generated by Django 3.2 on 2021-12-27 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_coupon_list_ok'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon_list',
            name='ok',
        ),
    ]
