# Generated by Django 3.2 on 2021-12-27 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_coupon_list_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon_list',
            name='coupon',
        ),
    ]
