# Generated by Django 3.2 on 2021-12-28 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_remove_coupon_list_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon_list',
            name='user',
        ),
    ]
