# Generated by Django 3.2 on 2021-12-28 03:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0032_remove_coupon_list_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon_list',
            name='coupons',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='products.coupon'),
        ),
        migrations.AddField(
            model_name='coupon_list',
            name='user',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
