# Generated by Django 3.2 on 2021-12-28 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_auto_20211228_0355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon_list',
            name='coupons',
        ),
    ]
