# Generated by Django 3.2 on 2021-12-28 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_remove_coupon_list_coupons'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon_list',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
