# Generated by Django 3.2 on 2021-12-28 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_coupon_list_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon_list',
            name='price',
        ),
        migrations.AddField(
            model_name='coupon_list',
            name='coupons',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='products.coupon'),
        ),
    ]
