# Generated by Django 3.2 on 2021-12-28 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_auto_20211228_0514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon_list',
            name='coupons',
        ),
    ]
