# Generated by Django 3.2 on 2021-12-28 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0037_remove_coupon_list_coupons'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon_list',
            name='coupon_use',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='products.coupon'),
        ),
    ]
