# Generated by Django 3.2 on 2021-12-28 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_coupon_list_coupon_use'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon_list',
            name='coupon_use',
        ),
    ]
