# Generated by Django 3.2 on 2021-12-28 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0040_coupon_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='user',
        ),
        migrations.AddField(
            model_name='coupon_list',
            name='coupon_use',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='products.coupon'),
        ),
    ]
