# Generated by Django 3.2 on 2022-01-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0043_remove_orderitems_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='placed', max_length=100),
        ),
    ]
