# Generated by Django 3.2 on 2022-01-09 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0045_products_special_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycart',
            name='guest_user',
            field=models.CharField(default=True, max_length=150),
        ),
    ]
