# Generated by Django 3.2 on 2022-01-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0046_mycart_guest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='wlist',
            name='guest_user',
            field=models.CharField(default=True, max_length=150),
        ),
    ]
